<a href="https://colab.research.google.com/github/vanshika14168/Data-structure/blob/main/secondEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("insurance.csv")

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
0,56,Female,24.6,Yes,West,Car,220000,0
1,68,Male,21.4,Yes,West,Bike,357000,1
2,21,Female,15.2,No,North,Bike,545000,0
3,43,Female,29.4,No,West,Car,249000,0
4,37,Female,36.5,No,West,Car,413000,1
...,...,...,...,...,...,...,...,...
595,54,Male,32.7,Yes,West,Car,446000,0
596,40,Male,31.1,No,North,Car,406000,0
597,60,Male,22.2,No,West,Car,380000,0
598,69,Male,28.3,No,East,Car,482000,0
599,65,Male,26.3,No,South,Bike,483000,0

In [ ]:
df=pd.read_csv("insurance.csv")

In [ ]:
df.head()

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
0,56,Female,24.6,Yes,West,Car,220000,0
1,68,Male,21.4,Yes,West,Bike,357000,1
2,21,Female,15.2,No,North,Bike,545000,0
3,43,Female,29.4,No,West,Car,249000,0
4,37,Female,36.5,No,West,Car,413000,1

In [ ]:
df.head(10)

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
0,56,Female,24.6,Yes,West,Car,220000,0
1,68,Male,21.4,Yes,West,Bike,357000,1
2,21,Female,15.2,No,North,Bike,545000,0
3,43,Female,29.4,No,West,Car,249000,0
4,37,Female,36.5,No,West,Car,413000,1
5,43,Male,15.0,No,North,Bike,157000,0
6,56,Male,28.1,No,South,Truck,351000,0
7,24,Female,29.1,No,North,Car,465000,0
8,66,Female,26.1,No,North,Car,426000,0
9,56,Male,29.0,Yes,South,Car,292000,0

In [ ]:
df.sample()

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
241,45,Male,39.3,No,South,Bike,257000,0

In [ ]:
df.tail()

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
595,54,Male,32.7,Yes,West,Car,446000,0
596,40,Male,31.1,No,North,Car,406000,0
597,60,Male,22.2,No,West,Car,380000,0
598,69,Male,28.3,No,East,Car,482000,0
599,65,Male,26.3,No,South,Bike,483000,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              600 non-null    int64
 1   Gender           600 non-null    object
 2   BMI              600 non-null    float64
 3   Smoker           600 non-null    object
 4   Region           600 non-null    object
 5   Vehicle_Type     600 non-null    object
 6   Annual_Income    600 non-null    int64
 7   Insurance_Claim  600 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 37.6+ KB

In [ ]:
df.isnull()

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
595,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False
597,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Age                0
Gender             0
BMI                0
Smoker             0
Region             0
Vehicle_Type       0
Annual_Income      0
Insurance_Claim    0
dtype: int64

In [ ]:
df.tail(7)

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
593,19,Female,15.9,Yes,North,Car,437000,0
594,62,Male,24.8,Yes,North,Truck,396000,0
595,54,Male,32.7,Yes,West,Car,446000,0
596,40,Male,31.1,No,North,Car,406000,0
597,60,Male,22.2,No,West,Car,380000,0
598,69,Male,28.3,No,East,Car,482000,0
599,65,Male,26.3,No,South,Bike,483000,0

In [ ]:
df.sample(7)

,Age,Gender,BMI,Smoker,Region,Vehicle_Type,Annual_Income,Insurance_Claim
41,55,Male,22.5,No,South,Car,476000,0
339,34,Male,36.4,Yes,West,Car,372000,0
244,24,Male,35.1,No,North,Bike,451000,0
151,44,Female,22.4,No,North,Bike,589000,0
192,59,Male,32.3,No,East,Car,390000,0
82,38,Female,24.3,No,West,Bike,247000,0
269,50,Female,16.9,No,West,Car,322000,0

In [ ]:
#property
#number of rows and columns
df.shape

(600, 8)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#analiysis on single column univaraint,analysis on two column bivariant,analysis on multi column multi variant

In [ ]:
df['Age']

0      56
1      68
2      21
3      43
4      37
       ..
595    54
596    40
597    60
598    69
599    65
Name: Age, Length: 600, dtype: int64

In [ ]:
df["Age"].max()

69

In [ ]:
df['Age'].min()

18

In [ ]:
df['Smoker'].sum()

'YesYesNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoYesNoNoNoNoYesYesNoNoNoYesNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoYesNoYesNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoYesNoNoNoNoYesNoNoYesYesNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoYesYesNoNoNoYesNoYesYesYesYesYesNoYesNoYesNoNoYesNoNoNoNoYesNoNoYesNoNoNoYesNoNoNoYesYesYesNoNoYesNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoYesNoNoYesYesYesNoYesNoNoYesNoYesNoNoNoNoYesNoNoNoYesNoNoNoNoYesNoNoYesNoNoNoNoNoYesNoNoNoYesNoNoNoNoNoNoNoNoYesYesNoNoYesNoNoNoNoNoNoYesNoYesNoNoNoNoNoYesNoNoYesNoYesNoNoNoNoYesNoNoNoNoYesNoNoNoNoNoNoYesNoNoNoNoNoNoNoYesNoYesNoNoYesYesNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoYesNoNoNoNoYesNoNoNoNoNoNoYesNoYesNoNoNoNoNoNoNoYesNoNoNoYesNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoYesNoYesYesYesNoNoNoNoYesYesNoNoNoNoYesYesYesNoNoNoNoYesNoYesNoNoNoNoNoNoNoNoYesYesNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoYesYesYesNoNoNoYesNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoNoNoNoNoNoYesYesYesNoYesNoYesNoYesNoNoYesNoNoNoNoNoYesNoYesNoYesNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoNoNoYesNoNoYesNoNoNoNoYesNoNoNoNoNoNoYesYesNoNoYesNoNoNoNoYesNoNoNoNoNoNoYesNoNoNoNoNoYesYesYesYesNoNoNoNo'

In [ ]:
df['Annual_Income'].sum()

np.int64(244789000)